# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Input_Window(object):
    def setupUi(self, Auto_Viber):
        Auto_Viber.setObjectName("Auto_Viber")
        Auto_Viber.resize(506, 275)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Auto_Viber)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 441, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(Auto_Viber)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 90, 311, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(25)
        self.spinBox.setValue(1)
        self.verticalLayout_2.addWidget(self.spinBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Auto_Viber)
        self.buttonBox.setGeometry(QtCore.QRect(260, 230, 210, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Auto_Viber)
        QtCore.QMetaObject.connectSlotsByName(Auto_Viber)

    def retranslateUi(self, Auto_Viber):
        _translate = QtCore.QCoreApplication.translate
        Auto_Viber.setWindowTitle(_translate("Auto_Viber", "Form"))
        self.pushButton.setText(_translate("Auto_Viber", "Выбрать"))

